/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 02 21:35:29 GMT 2017
 */

package models;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import models.Card;
import models.Suit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Card_ESTest extends Card_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Suit suit0 = Suit.Hearts;
      Card card0 = new Card((-90), suit0);
      String string0 = card0.toString();
      assertEquals("-90Hearts", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Suit suit0 = Suit.Copas;
      Card card0 = new Card(0, suit0);
      int int0 = card0.getValue();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Suit suit0 = Suit.Hearts;
      Card card0 = new Card((-90), suit0);
      int int0 = card0.getValue();
      assertEquals((-90), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Suit suit0 = Suit.Hearts;
      Card card0 = new Card((-90), suit0);
      card0.getSuit();
      assertEquals((-90), card0.value);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Suit suit0 = Suit.Spades;
      Card card0 = new Card((-25), suit0);
      card0.getSuit();
      assertEquals((-25), card0.value);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Card card0 = new Card((-25), (Suit) null);
      card0.getSuit();
      assertEquals((-25), card0.value);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Card card0 = new Card((-25), (Suit) null);
      // Undeclared exception!
      try { 
        card0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("models.Card", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Suit suit0 = Suit.Spades;
      Card card0 = new Card(4, suit0);
      int int0 = card0.getValue();
      assertEquals(4, int0);
  }
}
